### NumPy Tutorial
Date 30/01/2025

In [2]:
import numpy as np

# Creating Arrays
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)

# Array of zeros
zeros = np.zeros((3, 3))
print("Array of zeros:\n", zeros)

# Array of ones
ones = np.ones((2, 4))
print("Array of ones:\n", ones)

# Array of a constant value
full = np.full((2, 2), 7)
print("Array of constant value 7:\n", full)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Array with range of values:", range_arr)

# Array with random values
random_arr = np.random.random((3, 3))
print("Array with random values:\n", random_arr)



1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of constant value 7:
 [[7 7]
 [7 7]]
Array with range of values: [0 2 4 6 8]
Array with random values:
 [[0.88898799 0.83212174 0.1362632 ]
 [0.47024533 0.14384362 0.38542538]
 [0.09953079 0.3312474  0.77825431]]


In [3]:
# Basic Operations
# Element-wise addition
add = arr1 + 2
print("Element-wise addition:", add)

# Element-wise subtraction
sub = arr1 - 2
print("Element-wise subtraction:", sub)

# Element-wise multiplication
mul = arr1 * 2
print("Element-wise multiplication:", mul)

# Element-wise division
div = arr1 / 2
print("Element-wise division:", div)



Element-wise addition: [3 4 5 6 7]
Element-wise subtraction: [-1  0  1  2  3]
Element-wise multiplication: [ 2  4  6  8 10]
Element-wise division: [0.5 1.  1.5 2.  2.5]


In [4]:
# Array slicing
sliced_arr = arr1[1:4]
print("Sliced array:", sliced_arr)

# Reshaping arrays
reshaped_arr = arr2.reshape(3, 2)
print("Reshaped array:\n", reshaped_arr)

# Array concatenation
concat_arr = np.concatenate((arr1, [6, 7, 8]))
print("Concatenated array:", concat_arr)

# Array statistics
mean = np.mean(arr1)
print("Mean of arr1:", mean)

std_dev = np.std(arr1)
print("Standard deviation of arr1:", std_dev)

sum_arr = np.sum(arr1)
print("Sum of arr1:", sum_arr)



Sliced array: [2 3 4]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Concatenated array: [1 2 3 4 5 6 7 8]
Mean of arr1: 3.0
Standard deviation of arr1: 1.4142135623730951
Sum of arr1: 15


In [9]:
# Linear algebra operations
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
mat_mul = np.dot(mat1, mat2)
print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
print("Matrix multiplication:\n", mat_mul)

# Transpose of a matrix
transpose = np.transpose(mat1)
print("Transpose of mat1:\n", transpose)

# Inverse of a matrix
inverse = np.linalg.inv(mat1)
print("Inverse of mat1:\n", inverse)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of mat1:
 [[1 3]
 [2 4]]
Inverse of mat1:
 [[-2.   1. ]
 [ 1.5 -0.5]]
